<h1><p><center style="background: linear-gradient(to right,white,green);color: transparent;font-family: Gabriola;color: navy;font-size: 210%;text-align: center;border-radius: 10px 70px">
 Extracting and Visualizing Stock Data
 

</center></p></h1>

<div style="border-radius: 5px; -webkit-border-radius: 5px; -moz-border-radius: 5px; font-family: cursive; border: 3px solid #008000; text-align: justify; color: black; font-size: 14px; padding: 10px; background:#F2FFFF">

 <!-- Title -->
 <p style="text-align: center; font-family: cursive; font-size: 16px; color: green; font-weight: bold;">
        Extracting and Visualizing Stock Data
    </p>

 <!-- Table of Contents -->
<h2>Table of Contents</h2>
    <div >
        <ul>
            <li>Define a Function that Makes a Graph</li>
            <li>Question 1: Use yfinance to Extract Stock Data</li>
            <li>Question 2: Use Webscraping to Extract Tesla Revenue Data</li>
            <li>Question 3: Use yfinance to Extract Stock Data</li>
            <li>Question 4: Use Webscraping to Extract GME Revenue Data</li>
            <li>Question 5: Plot Tesla Stock Graph</li>
            <li>Question 6: Plot GameStop Stock Graph</li>
        </ul>
    </div>
</div>

In [1]:
import yfinance as yf
import pandas as pd
import requests
from bs4 import BeautifulSoup
import plotly.graph_objects as go
from plotly.subplots import make_subplots


import warnings
# Ignore all warnings
warnings.filterwarnings("ignore", category=FutureWarning)

<h1><p><center style="background: linear-gradient(to right,white,green);color: transparent;font-family: Gabriola;color: navy;font-size: 80%;text-align: center;border-radius: 10px 70px">
      Question 1: Use yfinance to Extract Stock Data 
</center></p></h1>

In [2]:
# -------------------------------
#  yf.download()
# -------------------------------
data_download = yf.download("TSLA", start="2023-01-01", end="2025-11-17", interval="1wk")
print("=== yf.download() ===")
print(data_download.head())

[*********************100%***********************]  1 of 1 completed

=== yf.download() ===
Price            Close        High         Low        Open      Volume
Ticker            TSLA        TSLA        TSLA        TSLA        TSLA
Date
2023-01-01  113.059998  118.800003  101.809998  118.470001   790689200
2023-01-08  122.400002  125.949997  114.919998  118.959999   891852300
2023-01-15  133.419998  136.679993  124.309998  125.699997   691307300
2023-01-22  177.899994  180.679993  134.270004  135.869995  1095958300
2023-01-29  189.979996  199.000000  162.779999  178.050003  1091608900

In [9]:
# -------------------------------
#  yf.Ticker()
# -------------------------------
tesla = yf.Ticker("TSLA")

# data
data_ticker = tesla.history(start="2023-01-01", end="2025-11-17", interval="1wk")
print("\n=== yf.Ticker().history() ===")
data_ticker.reset_index(inplace = True)
data_ticker.head()

=== yf.Ticker().history() ===

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits
0,2023-01-01 00:00:00-05:00,118.470001,118.800003,101.809998,113.059998,790689200,0.0,0.0
1,2023-01-08 00:00:00-05:00,118.959999,125.949997,114.919998,122.400002,891852300,0.0,0.0
2,2023-01-15 00:00:00-05:00,125.699997,136.679993,124.309998,133.419998,691307300,0.0,0.0
3,2023-01-22 00:00:00-05:00,135.869995,180.679993,134.270004,177.899994,1095958300,0.0,0.0
4,2023-01-29 00:00:00-05:00,178.050003,199.000000,162.779999,189.979996,1091608900,0.0,0.0

In [10]:


#  information
info = tesla.info
print("\n=== Info of Comp ===")
print(info['longName'], "-", info['sector'], "-", info['industry'])

# Taking dividends
dividends = tesla.dividends
print("\n=== dividends ===")
print(dividends.head())

# Taking stock splits
splits = tesla.splits
print("\n=== stock splits ===")
splits.reset_index()
print(splits.head())

=== Info of Comp ===
Tesla, Inc. - Consumer Cyclical - Auto Manufacturers

=== dividends ===
Series([], Name: Dividends, dtype: float64)

=== stock splits ===
Date
2020-08-31 00:00:00-04:00    5.0
2022-08-25 00:00:00-04:00    3.0
Name: Stock Splits, dtype: float64

<h1><p><center style="background: linear-gradient(to right,white,green);color: transparent;font-family: Gabriola;color: navy;font-size: 80%;text-align: center;border-radius: 10px 70px">
   Question 2: Use Webscraping to Extract Tesla Revenue Data

</center></p></h1>

In [12]:
URL = 'https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0220EN-SkillsNetwork/labs/project/revenue.htm'

response = requests.get(URL)

In [13]:

# --------------------------
#  response.text
# --------------------------
soup_text = BeautifulSoup(response.text, "html.parser")

print("=== با response.text ===")
print(soup_text.prettify()[:300])

=== با response.text ===
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js">
 <!--<![endif]-->
 <head>

In [14]:

# --------------------------
#  response.content
# --------------------------
soup_content = BeautifulSoup(response.content, "html.parser")
print("\n=== با response.content ===")
print(soup_content.prettify()[:300])  # نمایش 300 کاراکتر اول

=== با response.content ===
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js">
 <!--<![endif]-->
 <head>

In [32]:
tables = soup_text.find_all("table")
tables

[<table class="historical_data_table table">
 <thead>
 <tr>
 <th colspan="2" style="text-align:center">Tesla Annual Revenue<br/><span style="font-size:14px;">(Millions of US $)</span></th>
 </tr>
 </thead>
 <tbody>
 <tr>
 <td style="text-align:center">2021</td>
 <td style="text-align:center">$53,823</td>
 </tr>
 <tr>
 <td style="text-align:center">2020</td>
 <td style="text-align:center">$31,536</td>
 </tr>
 <tr>
 <td style="text-align:center">2019</td>
 <td style="text-align:center">$24,578</td>
 </tr>
 <tr>
 <td style="text-align:center">2018</td>
 <td style="text-align:center">$21,461</td>
 </tr>
 <tr>
 <td style="text-align:center">2017</td>
 <td style="text-align:center">$11,759</td>
 </tr>
 <tr>
 <td style="text-align:center">2016</td>
 <td style="text-align:center">$7,000</td>
 </tr>
 <tr>
 <td style="text-align:center">2015</td>
 <td style="text-align:center">$4,046</td>
 </tr>
 <tr>
 <td style="text-align:center">2014</td>
 <td style="text-align:center">$3,198</td>
 </tr>
 <tr>
 <td style="text-align:center">2013</td>
 <td style="text-align:center">$2,013</td>
 </tr>
 <tr>
 <td style="text-align:center">2012</td>
 <td style="text-align:center">$413</td>
 </tr>
 <tr>
 <td style="text-align:center">2011</td>
 <td style="text-align:center">$204</td>
 </tr>
 <tr>
 <td style="text-align:center">2010</td>
 <td style="text-align:center">$117</td>
 </tr>
 <tr>
 <td style="text-align:center">2009</td>
 <td style="text-align:center">$112</td>
 </tr>
 </tbody>
 </table>,
 <table class="historical_data_table table">
 <thead>
 <tr>
 <th colspan="2" style="text-align:center">Tesla Quarterly Revenue<br/><span style="font-size:14px;">(Millions of US $)</span></th>
 </tr>
 </thead>
 <tbody>
 <tr>
 <td style="text-align:center">2022-09-30</td>
 <td style="text-align:center">$21,454</td>
 </tr>
 <tr>
 <td style="text-align:center">2022-06-30</td>
 <td style="text-align:center">$16,934</td>
 </tr>
 <tr>
 <td style="text-align:center">2022-03-31</td>
 <td style="text-align:center">$18,756</td>
 </tr>
 <tr>
 <td style="text-align:center">2021-12-31</td>
 <td style="text-align:center">$17,719</td>
 </tr>
 <tr>
 <td style="text-align:center">2021-09-30</td>
 <td style="text-align:center">$13,757</td>
 </tr>
 <tr>
 <td style="text-align:center">2021-06-30</td>
 <td style="text-align:center">$11,958</td>
 </tr>
 <tr>
 <td style="text-align:center">2021-03-31</td>
 <td style="text-align:center">$10,389</td>
 </tr>
 <tr>
 <td style="text-align:center">2020-12-31</td>
 <td style="text-align:center">$10,744</td>
 </tr>
 <tr>
 <td style="text-align:center">2020-09-30</td>
 <td style="text-align:center">$8,771</td>
 </tr>
 <tr>
 <td style="text-align:center">2020-06-30</td>
 <td style="text-align:center">$6,036</td>
 </tr>
 <tr>
 <td style="text-align:center">2020-03-31</td>
 <td style="text-align:center">$5,985</td>
 </tr>
 <tr>
 <td style="text-align:center">2019-12-31</td>
 <td style="text-align:center">$7,384</td>
 </tr>
 <tr>
 <td style="text-align:center">2019-09-30</td>
 <td style="text-align:center">$6,303</td>
 </tr>
 <tr>
 <td style="text-align:center">2019-06-30</td>
 <td style="text-align:center">$6,350</td>
 </tr>
 <tr>
 <td style="text-align:center">2019-03-31</td>
 <td style="text-align:center">$4,541</td>
 </tr>
 <tr>
 <td style="text-align:center">2018-12-31</td>
 <td style="text-align:center">$7,226</td>
 </tr>
 <tr>
 <td style="text-align:center">2018-09-30</td>
 <td style="text-align:center">$6,824</td>
 </tr>
 <tr>
 <td style="text-align:center">2018-06-30</td>
 <td style="text-align:center">$4,002</td>
 </tr>
 <tr>
 <td style="text-align:center">2018-03-31</td>
 <td style="text-align:center">$3,409</td>
 </tr>
 <tr>
 <td style="text-align:center">2017-12-31</td>
 <td style="text-align:center">$3,288</td>
 </tr>
 <tr>
 <td style="text-align:center">2017-09-30</td>
 <td style="text-align:center">$2,985</td>
 </tr>
 <tr>
 <td style="text-align:center">2017-06-30</td>
 <td style="text-align:center">$2,790</td>
 </tr>
 <tr>
 <td style="text-align:center">2017-03-31</td>
 <td style="text-align:center">$2,696</td>
 </tr>
 <tr>
 <td style="text-align:center">2016-12-31</td>
 <td style="text-align:center">$2,285</td>
 </tr>
 <tr>
 <td style="text-align:center">2016-09-30</td>
 <td style="text-align:center">$2,298</td>
 </tr>
 <tr>
 <td style="text-align:center">2016-06-30</td>
 <td style="text-align:center">$1,270</td>
 </tr>
 <tr>
 <td style="text-align:center">2016-03-31</td>
 <td style="text-align:center">$1,147</td>
 </tr>
 <tr>
 <td style="text-align:center">2015-12-31</td>
 <td style="text-align:center">$1,214</td>
 </tr>
 <tr>
 <td style="text-align:center">2015-09-30</td>
 <td style="text-align:center">$937</td>
 </tr>
 <tr>
 <td style="text-align:center">2015-06-30</td>
 <td style="text-align:center">$955</td>
 </tr>
 <tr>
 <td style="text-align:center">2015-03-31</td>
 <td style="text-align:center">$940</td>
 </tr>
 <tr>
 <td style="text-align:center">2014-12-31</td>
 <td style="text-align:center">$957</td>
 </tr>
 <tr>
 <td style="text-align:center">2014-09-30</td>
 <td style="text-align:center">$852</td>
 </tr>
 <tr>
 <td style="text-align:center">2014-06-30</td>
 <td style="text-align:center">$769</td>
 </tr>
 <tr>
 <td style="text-align:center">2014-03-31</td>
 <td style="text-align:center">$621</td>
 </tr>
 <tr>
 <td style="text-align:center">2013-12-31</td>
 <td style="text-align:center">$615</td>
 </tr>
 <tr>
 <td style="text-align:center">2013-09-30</td>
 <td style="text-align:center">$431</td>
 </tr>
 <tr>
 <td style="text-align:center">2013-06-30</td>
 <td style="text-align:center">$405</td>
 </tr>
 <tr>
 <td style="text-align:center">2013-03-31</td>
 <td style="text-align:center">$562</td>
 </tr>
 <tr>
 <td style="text-align:center">2012-12-31</td>
 <td style="text-align:center">$306</td>
 </tr>
 <tr>
 <td style="text-align:center">2012-09-30</td>
 <td style="text-align:center">$50</td>
 </tr>
 <tr>
 <td style="text-align:center">2012-06-30</td>
 <td style="text-align:center">$27</td>
 </tr>
 <tr>
 <td style="text-align:center">2012-03-31</td>
 <td style="text-align:center">$30</td>
 </tr>
 <tr>
 <td style="text-align:center">2011-12-31</td>
 <td style="text-align:center">$39</td>
 </tr>
 <tr>
 <td style="text-align:center">2011-09-30</td>
 <td style="text-align:center">$58</td>
 </tr>
 <tr>
 <td style="text-align:center">2011-06-30</td>
 <td style="text-align:center">$58</td>
 </tr>
 <tr>
 <td style="text-align:center">2011-03-31</td>
 <td style="text-align:center">$49</td>
 </tr>
 <tr>
 <td style="text-align:center">2010-12-31</td>
 <td style="text-align:center">$36</td>
 </tr>
 <tr>
 <td style="text-align:center">2010-09-30</td>
 <td style="text-align:center">$31</td>
 </tr>
 <tr>
 <td style="text-align:center">2010-06-30</td>
 <td style="text-align:center">$28</td>
 </tr>
 <tr>
 <td style="text-align:center">2010-03-31</td>
 <td style="text-align:center">$21</td>
 </tr>
 <tr>
 <td style="text-align:center">2009-12-31</td>
 <td style="text-align:center"></td>
 </tr>
 <tr>
 <td style="text-align:center">2009-09-30</td>
 <td style="text-align:center">$46</td>
 </tr>
 <tr>
 <td style="text-align:center">2009-06-30</td>
 <td style="text-align:center">$27</td>
 </tr>
 </tbody>
 </table>,
 <table class="historical_data_table table">
 <thead>
 <tr>
 <th style="text-align:center">Sector</th>
 <th style="text-align:center">Industry</th>
 <th style="text-align:center">Market Cap</th>
 <th style="text-align:center">Revenue</th>
 </tr>
 </thead>
 <tbody>
 <tr>
 <td style="text-align:center"><a href="https://www.macrotrends.net/stocks/sector/5/auto-tires-trucks">Auto/Tires/Trucks</a></td>
 <td style="text-align:center"><a href="https://www.macrotrends.net/stocks/industry/7/">Auto Manufacturers - Domestic</a></td>
 <td style="text-align:center">$549.575B</td>
 <td style="text-align:center">$53.823B</td>
 </tr>
 <tr>
 <td colspan="4" style="padding:15px;">
 <span>Tesla is the market leader in battery-powered electric car sales in the United States, with roughly 70% market share. The company's flagship Model 3 is the best-selling EV model in the United States. Tesla, which has managed to garner the reputation of a gold standard over the years, is now a far bigger entity that what it started off since its IPO in 2010, with its market cap crossing $1 trillion for the first time in October 2021.? The EV king's market capitalization is more than the combined value of legacy automakers including Toyota, Volkswagen, Daimler, General Motors and Ford.Over the years, Tesla has shifted from developing niche products for affluent buyers to making more affordable EVs for the masses. The firm's three-pronged business model approach of direct sales, servicing, and charging its EVs sets it apart from other carmakers. Tesla, which is touted as the clean energy revolutionary automaker, is much more than just a car manufacturer.</span>
 </td>
 </tr>
 </tbody>
 </table>,
 <table class="historical_data_table table">
 <thead>
 <tr>
 <th style="text-align:center; width:40%;">Stock Name</th>
 <th style="text-align:center; width:20%;">Country</th>
 <th style="text-align:center; width:20%;">Market Cap</th>
 <th style="text-align:center; width:20%;">PE Ratio</th>
 </tr>
 </thead>
 <tbody>
 <tr>
 <td style="text-align:left"><a href="/stocks/charts/GM/general-motors/revenue">General Motors (GM)</a></td>
 <td style="text-align:center">United States</td>
 <td style="text-align:center">$53.930B</td>
 <td style="text-align:center">5.56</td>
 </tr>
 <tr>
 <td style="text-align:left"><a href="/stocks/charts/F/ford-motor/revenue">Ford Motor (F)</a></td>
 <td style="text-align:center">United States</td>
 <td style="text-align:center">$52.668B</td>
 <td style="text-align:center">8.09</td>
 </tr>
 <tr>
 <td style="text-align:left"><a href="/stocks/charts/HOG/harley-davidson/revenue">Harley-Davidson (HOG)</a></td>
 <td style="text-align:center">United States</td>
 <td style="text-align:center">$6.762B</td>
 <td style="text-align:center">9.56</td>
 </tr>
 <tr>
 <td style="text-align:left"><a href="/stocks/charts/PII/polaris/revenue">Polaris (PII)</a></td>
 <td style="text-align:center">United States</td>
 <td style="text-align:center">$6.267B</td>
 <td style="text-align:center">11.86</td>
 </tr>
 <tr>
 <td style="text-align:left"><a href="/stocks/charts/IAA/iaa/revenue">IAA (IAA)</a></td>
 <td style="text-align:center">United States</td>
 <td style="text-align:center">$5.134B</td>
 <td style="text-align:center">16.40</td>
 </tr>
 <tr>
 <td style="text-align:left"><a href="/stocks/charts/FSR/fisker/revenue">Fisker (FSR)</a></td>
 <td style="text-align:center">United States</td>
 <td style="text-align:center">$2.261B</td>
 <td style="text-align:center">0.00</td>
 </tr>
 <tr>
 <td style="text-align:left"><a href="/stocks/charts/LEV/lion-electric/revenue">Lion Electric (LEV)</a></td>
 <td style="text-align:center">Canada</td>
 <td style="text-align:center">$0.551B</td>
 <td style="text-align:center">0.00</td>
 </tr>
 <tr>
 <td style="text-align:left"><a href="/stocks/charts/VLTA/volta/revenue">Volta (VLTA)</a></td>
 <td style="text-align:center">United States</td>
 <td style="text-align:center">$0.071B</td>
 <td style="text-align:center">0.00</td>
 </tr>
 <tr>
 <td style="text-align:left"><a href="/stocks/charts/BRDS/bird-global/revenue">Bird Global (BRDS)</a></td>
 <td style="text-align:center">United States</td>
 <td style="text-align:center">$0.054B</td>
 <td style="text-align:center">0.00</td>
 </tr>
 <tr>
 <td style="text-align:left"><a href="/stocks/charts/ZEV/lightning-emotors/revenue">Lightning EMotors (ZEV)</a></td>
 <td style="text-align:center">United States</td>
 <td style="text-align:center">$0.043B</td>
 <td style="text-align:center">0.00</td>
 </tr>
 </tbody>
 </table>,
 <table class="table">
 <thead>
 <tr>
 <th>Link Preview</th>
 <th>HTML Code (Click to Copy)</th>
 </tr>
 </thead>
 <tbody>
 <tr>
 <td><a>Tesla Revenue 2010-2022 | TSLA</a></td>
 <td><input class="modal_link" size="60" type="text" value="&lt;a href='https://www.macrotrends.net/stocks/charts/TSLA/tesla/revenue'&gt;Tesla Revenue 2010-2022 | TSLA&lt;/a&gt;"/></td>
 </tr>
 <tr>
 <td><a>Macrotrends</a></td>
 <td><input class="modal_link" size="60" type="text" value="&lt;a href='https://www.macrotrends.net/stocks/charts/TSLA/tesla/revenue'&gt;Macrotrends&lt;/a&gt;"/></td>
 </tr>
 <tr>
 <td><a>Source</a></td>
 <td><input class="modal_link" size="60" type="text" value="&lt;a href='https://www.macrotrends.net/stocks/charts/TSLA/tesla/revenue'&gt;Source&lt;/a&gt;"/></td>
 </tr>
 </tbody>
 </table>,
 <table class="table">
 <thead>
 <tr>
 <th>Link Preview</th>
 <th>HTML Code (Click to Copy)</th>
 </tr>
 </thead>
 <tbody>
 <tr>
 <td><a>Tesla Revenue 2010-2022 | TSLA</a></td>
 <td><input class="modal_link" size="50" type="text" value="&lt;a href='https://www.macrotrends.net/stocks/charts/TSLA/tesla/revenue'&gt;Tesla Revenue 2010-2022 | TSLA&lt;/a&gt;"/></td>
 </tr>
 <tr>
 <td><a>Macrotrends</a></td>
 <td><input class="modal_link" size="50" type="text" value="&lt;a href='https://www.macrotrends.net/stocks/charts/TSLA/tesla/revenue'&gt;Macrotrends&lt;/a&gt;"/></td>
 </tr>
 <tr>
 <td><a>Source</a></td>
 <td><input class="modal_link" size="50" type="text" value="&lt;a href='https://www.macrotrends.net/stocks/charts/TSLA/tesla/revenue'&gt;Source&lt;/a&gt;"/></td>
 </tr>
 </tbody>
 </table>]

In [57]:
rows = soup_text.find_all('tr')
rows

[<tr>
 <th colspan="2" style="text-align:center">Tesla Annual Revenue<br/><span style="font-size:14px;">(Millions of US $)</span></th>
 </tr>,
 <tr>
 <td style="text-align:center">2021</td>
 <td style="text-align:center">$53,823</td>
 </tr>,
 <tr>
 <td style="text-align:center">2020</td>
 <td style="text-align:center">$31,536</td>
 </tr>,
 <tr>
 <td style="text-align:center">2019</td>
 <td style="text-align:center">$24,578</td>
 </tr>,
 <tr>
 <td style="text-align:center">2018</td>
 <td style="text-align:center">$21,461</td>
 </tr>,
 <tr>
 <td style="text-align:center">2017</td>
 <td style="text-align:center">$11,759</td>
 </tr>,
 <tr>
 <td style="text-align:center">2016</td>
 <td style="text-align:center">$7,000</td>
 </tr>,
 <tr>
 <td style="text-align:center">2015</td>
 <td style="text-align:center">$4,046</td>
 </tr>,
 <tr>
 <td style="text-align:center">2014</td>
 <td style="text-align:center">$3,198</td>
 </tr>,
 <tr>
 <td style="text-align:center">2013</td>
 <td style="text-align:center">$2,013</td>
 </tr>,
 <tr>
 <td style="text-align:center">2012</td>
 <td style="text-align:center">$413</td>
 </tr>,
 <tr>
 <td style="text-align:center">2011</td>
 <td style="text-align:center">$204</td>
 </tr>,
 <tr>
 <td style="text-align:center">2010</td>
 <td style="text-align:center">$117</td>
 </tr>,
 <tr>
 <td style="text-align:center">2009</td>
 <td style="text-align:center">$112</td>
 </tr>,
 <tr>
 <th colspan="2" style="text-align:center">Tesla Quarterly Revenue<br/><span style="font-size:14px;">(Millions of US $)</span></th>
 </tr>,
 <tr>
 <td style="text-align:center">2022-09-30</td>
 <td style="text-align:center">$21,454</td>
 </tr>,
 <tr>
 <td style="text-align:center">2022-06-30</td>
 <td style="text-align:center">$16,934</td>
 </tr>,
 <tr>
 <td style="text-align:center">2022-03-31</td>
 <td style="text-align:center">$18,756</td>
 </tr>,
 <tr>
 <td style="text-align:center">2021-12-31</td>
 <td style="text-align:center">$17,719</td>
 </tr>,
 <tr>
 <td style="text-align:center">2021-09-30</td>
 <td style="text-align:center">$13,757</td>
 </tr>,
 <tr>
 <td style="text-align:center">2021-06-30</td>
 <td style="text-align:center">$11,958</td>
 </tr>,
 <tr>
 <td style="text-align:center">2021-03-31</td>
 <td style="text-align:center">$10,389</td>
 </tr>,
 <tr>
 <td style="text-align:center">2020-12-31</td>
 <td style="text-align:center">$10,744</td>
 </tr>,
 <tr>
 <td style="text-align:center">2020-09-30</td>
 <td style="text-align:center">$8,771</td>
 </tr>,
 <tr>
 <td style="text-align:center">2020-06-30</td>
 <td style="text-align:center">$6,036</td>
 </tr>,
 <tr>
 <td style="text-align:center">2020-03-31</td>
 <td style="text-align:center">$5,985</td>
 </tr>,
 <tr>
 <td style="text-align:center">2019-12-31</td>
 <td style="text-align:center">$7,384</td>
 </tr>,
 <tr>
 <td style="text-align:center">2019-09-30</td>
 <td style="text-align:center">$6,303</td>
 </tr>,
 <tr>
 <td style="text-align:center">2019-06-30</td>
 <td style="text-align:center">$6,350</td>
 </tr>,
 <tr>
 <td style="text-align:center">2019-03-31</td>
 <td style="text-align:center">$4,541</td>
 </tr>,
 <tr>
 <td style="text-align:center">2018-12-31</td>
 <td style="text-align:center">$7,226</td>
 </tr>,
 <tr>
 <td style="text-align:center">2018-09-30</td>
 <td style="text-align:center">$6,824</td>
 </tr>,
 <tr>
 <td style="text-align:center">2018-06-30</td>
 <td style="text-align:center">$4,002</td>
 </tr>,
 <tr>
 <td style="text-align:center">2018-03-31</td>
 <td style="text-align:center">$3,409</td>
 </tr>,
 <tr>
 <td style="text-align:center">2017-12-31</td>
 <td style="text-align:center">$3,288</td>
 </tr>,
 <tr>
 <td style="text-align:center">2017-09-30</td>
 <td style="text-align:center">$2,985</td>
 </tr>,
 <tr>
 <td style="text-align:center">2017-06-30</td>
 <td style="text-align:center">$2,790</td>
 </tr>,
 <tr>
 <td style="text-align:center">2017-03-31</td>
 <td style="text-align:center">$2,696</td>
 </tr>,
 <tr>
 <td style="text-align:center">2016-12-31</td>
 <td style="text-align:center">$2,285</td>
 </tr>,
 <tr>
 <td style="text-align:center">2016-09-30</td>
 <td style="text-align:center">$2,298</td>
 </tr>,
 <tr>
 <td style="text-align:center">2016-06-30</td>
 <td style="text-align:center">$1,270</td>
 </tr>,
 <tr>
 <td style="text-align:center">2016-03-31</td>
 <td style="text-align:center">$1,147</td>
 </tr>,
 <tr>
 <td style="text-align:center">2015-12-31</td>
 <td style="text-align:center">$1,214</td>
 </tr>,
 <tr>
 <td style="text-align:center">2015-09-30</td>
 <td style="text-align:center">$937</td>
 </tr>,
 <tr>
 <td style="text-align:center">2015-06-30</td>
 <td style="text-align:center">$955</td>
 </tr>,
 <tr>
 <td style="text-align:center">2015-03-31</td>
 <td style="text-align:center">$940</td>
 </tr>,
 <tr>
 <td style="text-align:center">2014-12-31</td>
 <td style="text-align:center">$957</td>
 </tr>,
 <tr>
 <td style="text-align:center">2014-09-30</td>
 <td style="text-align:center">$852</td>
 </tr>,
 <tr>
 <td style="text-align:center">2014-06-30</td>
 <td style="text-align:center">$769</td>
 </tr>,
 <tr>
 <td style="text-align:center">2014-03-31</td>
 <td style="text-align:center">$621</td>
 </tr>,
 <tr>
 <td style="text-align:center">2013-12-31</td>
 <td style="text-align:center">$615</td>
 </tr>,
 <tr>
 <td style="text-align:center">2013-09-30</td>
 <td style="text-align:center">$431</td>
 </tr>,
 <tr>
 <td style="text-align:center">2013-06-30</td>
 <td style="text-align:center">$405</td>
 </tr>,
 <tr>
 <td style="text-align:center">2013-03-31</td>
 <td style="text-align:center">$562</td>
 </tr>,
 <tr>
 <td style="text-align:center">2012-12-31</td>
 <td style="text-align:center">$306</td>
 </tr>,
 <tr>
 <td style="text-align:center">2012-09-30</td>
 <td style="text-align:center">$50</td>
 </tr>,
 <tr>
 <td style="text-align:center">2012-06-30</td>
 <td style="text-align:center">$27</td>
 </tr>,
 <tr>
 <td style="text-align:center">2012-03-31</td>
 <td style="text-align:center">$30</td>
 </tr>,
 <tr>
 <td style="text-align:center">2011-12-31</td>
 <td style="text-align:center">$39</td>
 </tr>,
 <tr>
 <td style="text-align:center">2011-09-30</td>
 <td style="text-align:center">$58</td>
 </tr>,
 <tr>
 <td style="text-align:center">2011-06-30</td>
 <td style="text-align:center">$58</td>
 </tr>,
 <tr>
 <td style="text-align:center">2011-03-31</td>
 <td style="text-align:center">$49</td>
 </tr>,
 <tr>
 <td style="text-align:center">2010-12-31</td>
 <td style="text-align:center">$36</td>
 </tr>,
 <tr>
 <td style="text-align:center">2010-09-30</td>
 <td style="text-align:center">$31</td>
 </tr>,
 <tr>
 <td style="text-align:center">2010-06-30</td>
 <td style="text-align:center">$28</td>
 </tr>,
 <tr>
 <td style="text-align:center">2010-03-31</td>
 <td style="text-align:center">$21</td>
 </tr>,
 <tr>
 <td style="text-align:center">2009-12-31</td>
 <td style="text-align:center"></td>
 </tr>,
 <tr>
 <td style="text-align:center">2009-09-30</td>
 <td style="text-align:center">$46</td>
 </tr>,
 <tr>
 <td style="text-align:center">2009-06-30</td>
 <td style="text-align:center">$27</td>
 </tr>,
 <tr>
 <th style="text-align:center">Sector</th>
 <th style="text-align:center">Industry</th>
 <th style="text-align:center">Market Cap</th>
 <th style="text-align:center">Revenue</th>
 </tr>,
 <tr>
 <td style="text-align:center"><a href="https://www.macrotrends.net/stocks/sector/5/auto-tires-trucks">Auto/Tires/Trucks</a></td>
 <td style="text-align:center"><a href="https://www.macrotrends.net/stocks/industry/7/">Auto Manufacturers - Domestic</a></td>
 <td style="text-align:center">$549.575B</td>
 <td style="text-align:center">$53.823B</td>
 </tr>,
 <tr>
 <td colspan="4" style="padding:15px;">
 <span>Tesla is the market leader in battery-powered electric car sales in the United States, with roughly 70% market share. The company's flagship Model 3 is the best-selling EV model in the United States. Tesla, which has managed to garner the reputation of a gold standard over the years, is now a far bigger entity that what it started off since its IPO in 2010, with its market cap crossing $1 trillion for the first time in October 2021.? The EV king's market capitalization is more than the combined value of legacy automakers including Toyota, Volkswagen, Daimler, General Motors and Ford.Over the years, Tesla has shifted from developing niche products for affluent buyers to making more affordable EVs for the masses. The firm's three-pronged business model approach of direct sales, servicing, and charging its EVs sets it apart from other carmakers. Tesla, which is touted as the clean energy revolutionary automaker, is much more than just a car manufacturer.</span>
 </td>
 </tr>,
 <tr>
 <th style="text-align:center; width:40%;">Stock Name</th>
 <th style="text-align:center; width:20%;">Country</th>
 <th style="text-align:center; width:20%;">Market Cap</th>
 <th style="text-align:center; width:20%;">PE Ratio</th>
 </tr>,
 <tr>
 <td style="text-align:left"><a href="/stocks/charts/GM/general-motors/revenue">General Motors (GM)</a></td>
 <td style="text-align:center">United States</td>
 <td style="text-align:center">$53.930B</td>
 <td style="text-align:center">5.56</td>
 </tr>,
 <tr>
 <td style="text-align:left"><a href="/stocks/charts/F/ford-motor/revenue">Ford Motor (F)</a></td>
 <td style="text-align:center">United States</td>
 <td style="text-align:center">$52.668B</td>
 <td style="text-align:center">8.09</td>
 </tr>,
 <tr>
 <td style="text-align:left"><a href="/stocks/charts/HOG/harley-davidson/revenue">Harley-Davidson (HOG)</a></td>
 <td style="text-align:center">United States</td>
 <td style="text-align:center">$6.762B</td>
 <td style="text-align:center">9.56</td>
 </tr>,
 <tr>
 <td style="text-align:left"><a href="/stocks/charts/PII/polaris/revenue">Polaris (PII)</a></td>
 <td style="text-align:center">United States</td>
 <td style="text-align:center">$6.267B</td>
 <td style="text-align:center">11.86</td>
 </tr>,
 <tr>
 <td style="text-align:left"><a href="/stocks/charts/IAA/iaa/revenue">IAA (IAA)</a></td>
 <td style="text-align:center">United States</td>
 <td style="text-align:center">$5.134B</td>
 <td style="text-align:center">16.40</td>
 </tr>,
 <tr>
 <td style="text-align:left"><a href="/stocks/charts/FSR/fisker/revenue">Fisker (FSR)</a></td>
 <td style="text-align:center">United States</td>
 <td style="text-align:center">$2.261B</td>
 <td style="text-align:center">0.00</td>
 </tr>,
 <tr>
 <td style="text-align:left"><a href="/stocks/charts/LEV/lion-electric/revenue">Lion Electric (LEV)</a></td>
 <td style="text-align:center">Canada</td>
 <td style="text-align:center">$0.551B</td>
 <td style="text-align:center">0.00</td>
 </tr>,
 <tr>
 <td style="text-align:left"><a href="/stocks/charts/VLTA/volta/revenue">Volta (VLTA)</a></td>
 <td style="text-align:center">United States</td>
 <td style="text-align:center">$0.071B</td>
 <td style="text-align:center">0.00</td>
 </tr>,
 <tr>
 <td style="text-align:left"><a href="/stocks/charts/BRDS/bird-global/revenue">Bird Global (BRDS)</a></td>
 <td style="text-align:center">United States</td>
 <td style="text-align:center">$0.054B</td>
 <td style="text-align:center">0.00</td>
 </tr>,
 <tr>
 <td style="text-align:left"><a href="/stocks/charts/ZEV/lightning-emotors/revenue">Lightning EMotors (ZEV)</a></td>
 <td style="text-align:center">United States</td>
 <td style="text-align:center">$0.043B</td>
 <td style="text-align:center">0.00</td>
 </tr>,
 <tr>
 <th>Link Preview</th>
 <th>HTML Code (Click to Copy)</th>
 </tr>,
 <tr>
 <td><a>Tesla Revenue 2010-2022 | TSLA</a></td>
 <td><input class="modal_link" size="60" type="text" value="&lt;a href='https://www.macrotrends.net/stocks/charts/TSLA/tesla/revenue'&gt;Tesla Revenue 2010-2022 | TSLA&lt;/a&gt;"/></td>
 </tr>,
 <tr>
 <td><a>Macrotrends</a></td>
 <td><input class="modal_link" size="60" type="text" value="&lt;a href='https://www.macrotrends.net/stocks/charts/TSLA/tesla/revenue'&gt;Macrotrends&lt;/a&gt;"/></td>
 </tr>,
 <tr>
 <td><a>Source</a></td>
 <td><input class="modal_link" size="60" type="text" value="&lt;a href='https://www.macrotrends.net/stocks/charts/TSLA/tesla/revenue'&gt;Source&lt;/a&gt;"/></td>
 </tr>,
 <tr>
 <th>Link Preview</th>
 <th>HTML Code (Click to Copy)</th>
 </tr>,
 <tr>
 <td><a>Tesla Revenue 2010-2022 | TSLA</a></td>
 <td><input class="modal_link" size="50" type="text" value="&lt;a href='https://www.macrotrends.net/stocks/charts/TSLA/tesla/revenue'&gt;Tesla Revenue 2010-2022 | TSLA&lt;/a&gt;"/></td>
 </tr>,
 <tr>
 <td><a>Macrotrends</a></td>
 <td><input class="modal_link" size="50" type="text" value="&lt;a href='https://www.macrotrends.net/stocks/charts/TSLA/tesla/revenue'&gt;Macrotrends&lt;/a&gt;"/></td>
 </tr>,
 <tr>
 <td><a>Source</a></td>
 <td><input class="modal_link" size="50" type="text" value="&lt;a href='https://www.macrotrends.net/stocks/charts/TSLA/tesla/revenue'&gt;Source&lt;/a&gt;"/></td>
 </tr>]

In [60]:
data = []
for row in rows[1:]:
    cols = row.find_all('td')
    cols_text = [col.text.strip() for col in cols]
    data.append(cols_text)

In [62]:

cleaned_data = []
for row in data:
    row = row[:2]
    while len(row) < 2:
        row.append(None)
    cleaned_data.append(row)

In [107]:
tesla_revenue= pd.DataFrame(cleaned_data, columns=['Date', 'Revenue'])
tesla_revenue['Revenue'] = tesla_revenue['Revenue'].replace(r'[\$,]', '', regex=True)
tesla_revenue.head()

   Date Revenue
0  2021   53823
1  2020   31536
2  2019   24578
3  2018   21461
4  2017   11759

<h1><p><center style="background: linear-gradient(to right,white,green);color: transparent;font-family: Gabriola;color: navy;font-size: 80%;text-align: center;border-radius: 10px 70px">
   Question 3: Use yfinance to Extract Stock Data

</center></p></h1>

In [65]:
# -------------------------------
#  yf.Ticker()
# -------------------------------
gme = yf.Ticker("GME")

# data
gme_data= gme.history(start="2023-01-01", end="2025-11-17", interval="1wk")
print("\n=== yf.Ticker().history() ===")
gme_data.reset_index(inplace = True)
gme_data.head()

=== yf.Ticker().history() ===

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits
0,2023-01-01 00:00:00-05:00,18.639999,19.260000,15.410000,16.459999,19964100,0.0,0.0
1,2023-01-08 00:00:00-05:00,16.650000,21.110001,16.250000,20.490000,27702900,0.0,0.0
2,2023-01-15 00:00:00-05:00,20.490000,22.150000,18.820000,19.610001,19123600,0.0,0.0
3,2023-01-22 00:00:00-05:00,19.500000,23.309999,19.370001,22.820000,28496100,0.0,0.0
4,2023-01-29 00:00:00-05:00,22.500000,24.400000,20.549999,22.250000,25187800,0.0,0.0

<h1><p><center style="background: linear-gradient(to right,white,green);color: transparent;font-family: Gabriola;color: navy;font-size: 80%;text-align: center;border-radius: 10px 70px">
  Question 4: Use Webscraping to Extract GME Revenue Data

</center></p></h1>

In [93]:
URL = 'https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0220EN-SkillsNetwork/labs/project/stock.html'

response1 = requests.get(URL)

In [94]:

soup_text1 = BeautifulSoup(response1.text, "html.parser")

print("=== با response.text ===")
print(soup_text1.prettify()[:300])

=== با response.text ===
<!DOCTYPE html>
<!-- saved from url=(0105)https://web.archive.org/web/20200814131437/https://www.macrotrends.net/stocks/charts/GME/gamestop/revenue -->
<html class="js flexbox canvas canvastext webgl no-touch geolocation postmessage websqldatabase indexeddb hashchange history draganddrop websockets

In [95]:
tables = soup_text1.find_all('table')
revenue_table = tables[1]

revenue_table

<table class="historical_data_table table">
<thead>
<tr>
<th colspan="2" style="text-align:center">GameStop Quarterly Revenue<br/><span style="font-size:14px;">(Millions of US $)</span></th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center">2020-04-30</td>
<td style="text-align:center">$1,021</td>
</tr>
<tr>
<td style="text-align:center">2020-01-31</td>
<td style="text-align:center">$2,194</td>
</tr>
<tr>
<td style="text-align:center">2019-10-31</td>
<td style="text-align:center">$1,439</td>
</tr>
<tr>
<td style="text-align:center">2019-07-31</td>
<td style="text-align:center">$1,286</td>
</tr>
<tr>
<td style="text-align:center">2019-04-30</td>
<td style="text-align:center">$1,548</td>
</tr>
<tr>
<td style="text-align:center">2019-01-31</td>
<td style="text-align:center">$3,063</td>
</tr>
<tr>
<td style="text-align:center">2018-10-31</td>
<td style="text-align:center">$1,935</td>
</tr>
<tr>
<td style="text-align:center">2018-07-31</td>
<td style="text-align:center">$1,501</td>
</tr>
<tr>
<td style="text-align:center">2018-04-30</td>
<td style="text-align:center">$1,786</td>
</tr>
<tr>
<td style="text-align:center">2018-01-31</td>
<td style="text-align:center">$2,825</td>
</tr>
<tr>
<td style="text-align:center">2017-10-31</td>
<td style="text-align:center">$1,989</td>
</tr>
<tr>
<td style="text-align:center">2017-07-31</td>
<td style="text-align:center">$1,688</td>
</tr>
<tr>
<td style="text-align:center">2017-04-30</td>
<td style="text-align:center">$2,046</td>
</tr>
<tr>
<td style="text-align:center">2017-01-31</td>
<td style="text-align:center">$2,403</td>
</tr>
<tr>
<td style="text-align:center">2016-10-31</td>
<td style="text-align:center">$1,959</td>
</tr>
<tr>
<td style="text-align:center">2016-07-31</td>
<td style="text-align:center">$1,632</td>
</tr>
<tr>
<td style="text-align:center">2016-04-30</td>
<td style="text-align:center">$1,972</td>
</tr>
<tr>
<td style="text-align:center">2016-01-31</td>
<td style="text-align:center">$3,525</td>
</tr>
<tr>
<td style="text-align:center">2015-10-31</td>
<td style="text-align:center">$2,016</td>
</tr>
<tr>
<td style="text-align:center">2015-07-31</td>
<td style="text-align:center">$1,762</td>
</tr>
<tr>
<td style="text-align:center">2015-04-30</td>
<td style="text-align:center">$2,061</td>
</tr>
<tr>
<td style="text-align:center">2015-01-31</td>
<td style="text-align:center">$3,476</td>
</tr>
<tr>
<td style="text-align:center">2014-10-31</td>
<td style="text-align:center">$2,092</td>
</tr>
<tr>
<td style="text-align:center">2014-07-31</td>
<td style="text-align:center">$1,731</td>
</tr>
<tr>
<td style="text-align:center">2014-04-30</td>
<td style="text-align:center">$1,996</td>
</tr>
<tr>
<td style="text-align:center">2014-01-31</td>
<td style="text-align:center">$3,684</td>
</tr>
<tr>
<td style="text-align:center">2013-10-31</td>
<td style="text-align:center">$2,107</td>
</tr>
<tr>
<td style="text-align:center">2013-07-31</td>
<td style="text-align:center">$1,384</td>
</tr>
<tr>
<td style="text-align:center">2013-04-30</td>
<td style="text-align:center">$1,865</td>
</tr>
<tr>
<td style="text-align:center">2013-01-31</td>
<td style="text-align:center">$3,562</td>
</tr>
<tr>
<td style="text-align:center">2012-10-31</td>
<td style="text-align:center">$1,773</td>
</tr>
<tr>
<td style="text-align:center">2012-07-31</td>
<td style="text-align:center">$1,550</td>
</tr>
<tr>
<td style="text-align:center">2012-04-30</td>
<td style="text-align:center">$2,002</td>
</tr>
<tr>
<td style="text-align:center">2012-01-31</td>
<td style="text-align:center">$3,579</td>
</tr>
<tr>
<td style="text-align:center">2011-10-31</td>
<td style="text-align:center">$1,947</td>
</tr>
<tr>
<td style="text-align:center">2011-07-31</td>
<td style="text-align:center">$1,744</td>
</tr>
<tr>
<td style="text-align:center">2011-04-30</td>
<td style="text-align:center">$2,281</td>
</tr>
<tr>
<td style="text-align:center">2011-01-31</td>
<td style="text-align:center">$3,693</td>
</tr>
<tr>
<td style="text-align:center">2010-10-31</td>
<td style="text-align:center">$1,899</td>
</tr>
<tr>
<td style="text-align:center">2010-07-31</td>
<td style="text-align:center">$1,799</td>
</tr>
<tr>
<td style="text-align:center">2010-04-30</td>
<td style="text-align:center">$2,083</td>
</tr>
<tr>
<td style="text-align:center">2010-01-31</td>
<td style="text-align:center">$3,524</td>
</tr>
<tr>
<td style="text-align:center">2009-10-31</td>
<td style="text-align:center">$1,835</td>
</tr>
<tr>
<td style="text-align:center">2009-07-31</td>
<td style="text-align:center">$1,739</td>
</tr>
<tr>
<td style="text-align:center">2009-04-30</td>
<td style="text-align:center">$1,981</td>
</tr>
<tr>
<td style="text-align:center">2009-01-31</td>
<td style="text-align:center">$3,492</td>
</tr>
<tr>
<td style="text-align:center">2008-10-31</td>
<td style="text-align:center">$1,696</td>
</tr>
<tr>
<td style="text-align:center">2008-07-31</td>
<td style="text-align:center">$1,804</td>
</tr>
<tr>
<td style="text-align:center">2008-04-30</td>
<td style="text-align:center">$1,814</td>
</tr>
<tr>
<td style="text-align:center">2008-01-31</td>
<td style="text-align:center">$2,866</td>
</tr>
<tr>
<td style="text-align:center">2007-10-31</td>
<td style="text-align:center">$1,611</td>
</tr>
<tr>
<td style="text-align:center">2007-07-31</td>
<td style="text-align:center">$1,338</td>
</tr>
<tr>
<td style="text-align:center">2007-04-30</td>
<td style="text-align:center">$1,279</td>
</tr>
<tr>
<td style="text-align:center">2007-01-31</td>
<td style="text-align:center">$2,304</td>
</tr>
<tr>
<td style="text-align:center">2006-10-31</td>
<td style="text-align:center">$1,012</td>
</tr>
<tr>
<td style="text-align:center">2006-07-31</td>
<td style="text-align:center">$963</td>
</tr>
<tr>
<td style="text-align:center">2006-04-30</td>
<td style="text-align:center">$1,040</td>
</tr>
<tr>
<td style="text-align:center">2006-01-31</td>
<td style="text-align:center">$1,667</td>
</tr>
<tr>
<td style="text-align:center">2005-10-31</td>
<td style="text-align:center">$534</td>
</tr>
<tr>
<td style="text-align:center">2005-07-31</td>
<td style="text-align:center">$416</td>
</tr>
<tr>
<td style="text-align:center">2005-04-30</td>
<td style="text-align:center">$475</td>
</tr>
<tr>
<td style="text-align:center">2005-01-31</td>
<td style="text-align:center">$709</td>
</tr>
</tbody>
</table>

In [96]:
rows1 = revenue_table.find_all('tr')
rows1

[<tr>
 <th colspan="2" style="text-align:center">GameStop Quarterly Revenue<br/><span style="font-size:14px;">(Millions of US $)</span></th>
 </tr>,
 <tr>
 <td style="text-align:center">2020-04-30</td>
 <td style="text-align:center">$1,021</td>
 </tr>,
 <tr>
 <td style="text-align:center">2020-01-31</td>
 <td style="text-align:center">$2,194</td>
 </tr>,
 <tr>
 <td style="text-align:center">2019-10-31</td>
 <td style="text-align:center">$1,439</td>
 </tr>,
 <tr>
 <td style="text-align:center">2019-07-31</td>
 <td style="text-align:center">$1,286</td>
 </tr>,
 <tr>
 <td style="text-align:center">2019-04-30</td>
 <td style="text-align:center">$1,548</td>
 </tr>,
 <tr>
 <td style="text-align:center">2019-01-31</td>
 <td style="text-align:center">$3,063</td>
 </tr>,
 <tr>
 <td style="text-align:center">2018-10-31</td>
 <td style="text-align:center">$1,935</td>
 </tr>,
 <tr>
 <td style="text-align:center">2018-07-31</td>
 <td style="text-align:center">$1,501</td>
 </tr>,
 <tr>
 <td style="text-align:center">2018-04-30</td>
 <td style="text-align:center">$1,786</td>
 </tr>,
 <tr>
 <td style="text-align:center">2018-01-31</td>
 <td style="text-align:center">$2,825</td>
 </tr>,
 <tr>
 <td style="text-align:center">2017-10-31</td>
 <td style="text-align:center">$1,989</td>
 </tr>,
 <tr>
 <td style="text-align:center">2017-07-31</td>
 <td style="text-align:center">$1,688</td>
 </tr>,
 <tr>
 <td style="text-align:center">2017-04-30</td>
 <td style="text-align:center">$2,046</td>
 </tr>,
 <tr>
 <td style="text-align:center">2017-01-31</td>
 <td style="text-align:center">$2,403</td>
 </tr>,
 <tr>
 <td style="text-align:center">2016-10-31</td>
 <td style="text-align:center">$1,959</td>
 </tr>,
 <tr>
 <td style="text-align:center">2016-07-31</td>
 <td style="text-align:center">$1,632</td>
 </tr>,
 <tr>
 <td style="text-align:center">2016-04-30</td>
 <td style="text-align:center">$1,972</td>
 </tr>,
 <tr>
 <td style="text-align:center">2016-01-31</td>
 <td style="text-align:center">$3,525</td>
 </tr>,
 <tr>
 <td style="text-align:center">2015-10-31</td>
 <td style="text-align:center">$2,016</td>
 </tr>,
 <tr>
 <td style="text-align:center">2015-07-31</td>
 <td style="text-align:center">$1,762</td>
 </tr>,
 <tr>
 <td style="text-align:center">2015-04-30</td>
 <td style="text-align:center">$2,061</td>
 </tr>,
 <tr>
 <td style="text-align:center">2015-01-31</td>
 <td style="text-align:center">$3,476</td>
 </tr>,
 <tr>
 <td style="text-align:center">2014-10-31</td>
 <td style="text-align:center">$2,092</td>
 </tr>,
 <tr>
 <td style="text-align:center">2014-07-31</td>
 <td style="text-align:center">$1,731</td>
 </tr>,
 <tr>
 <td style="text-align:center">2014-04-30</td>
 <td style="text-align:center">$1,996</td>
 </tr>,
 <tr>
 <td style="text-align:center">2014-01-31</td>
 <td style="text-align:center">$3,684</td>
 </tr>,
 <tr>
 <td style="text-align:center">2013-10-31</td>
 <td style="text-align:center">$2,107</td>
 </tr>,
 <tr>
 <td style="text-align:center">2013-07-31</td>
 <td style="text-align:center">$1,384</td>
 </tr>,
 <tr>
 <td style="text-align:center">2013-04-30</td>
 <td style="text-align:center">$1,865</td>
 </tr>,
 <tr>
 <td style="text-align:center">2013-01-31</td>
 <td style="text-align:center">$3,562</td>
 </tr>,
 <tr>
 <td style="text-align:center">2012-10-31</td>
 <td style="text-align:center">$1,773</td>
 </tr>,
 <tr>
 <td style="text-align:center">2012-07-31</td>
 <td style="text-align:center">$1,550</td>
 </tr>,
 <tr>
 <td style="text-align:center">2012-04-30</td>
 <td style="text-align:center">$2,002</td>
 </tr>,
 <tr>
 <td style="text-align:center">2012-01-31</td>
 <td style="text-align:center">$3,579</td>
 </tr>,
 <tr>
 <td style="text-align:center">2011-10-31</td>
 <td style="text-align:center">$1,947</td>
 </tr>,
 <tr>
 <td style="text-align:center">2011-07-31</td>
 <td style="text-align:center">$1,744</td>
 </tr>,
 <tr>
 <td style="text-align:center">2011-04-30</td>
 <td style="text-align:center">$2,281</td>
 </tr>,
 <tr>
 <td style="text-align:center">2011-01-31</td>
 <td style="text-align:center">$3,693</td>
 </tr>,
 <tr>
 <td style="text-align:center">2010-10-31</td>
 <td style="text-align:center">$1,899</td>
 </tr>,
 <tr>
 <td style="text-align:center">2010-07-31</td>
 <td style="text-align:center">$1,799</td>
 </tr>,
 <tr>
 <td style="text-align:center">2010-04-30</td>
 <td style="text-align:center">$2,083</td>
 </tr>,
 <tr>
 <td style="text-align:center">2010-01-31</td>
 <td style="text-align:center">$3,524</td>
 </tr>,
 <tr>
 <td style="text-align:center">2009-10-31</td>
 <td style="text-align:center">$1,835</td>
 </tr>,
 <tr>
 <td style="text-align:center">2009-07-31</td>
 <td style="text-align:center">$1,739</td>
 </tr>,
 <tr>
 <td style="text-align:center">2009-04-30</td>
 <td style="text-align:center">$1,981</td>
 </tr>,
 <tr>
 <td style="text-align:center">2009-01-31</td>
 <td style="text-align:center">$3,492</td>
 </tr>,
 <tr>
 <td style="text-align:center">2008-10-31</td>
 <td style="text-align:center">$1,696</td>
 </tr>,
 <tr>
 <td style="text-align:center">2008-07-31</td>
 <td style="text-align:center">$1,804</td>
 </tr>,
 <tr>
 <td style="text-align:center">2008-04-30</td>
 <td style="text-align:center">$1,814</td>
 </tr>,
 <tr>
 <td style="text-align:center">2008-01-31</td>
 <td style="text-align:center">$2,866</td>
 </tr>,
 <tr>
 <td style="text-align:center">2007-10-31</td>
 <td style="text-align:center">$1,611</td>
 </tr>,
 <tr>
 <td style="text-align:center">2007-07-31</td>
 <td style="text-align:center">$1,338</td>
 </tr>,
 <tr>
 <td style="text-align:center">2007-04-30</td>
 <td style="text-align:center">$1,279</td>
 </tr>,
 <tr>
 <td style="text-align:center">2007-01-31</td>
 <td style="text-align:center">$2,304</td>
 </tr>,
 <tr>
 <td style="text-align:center">2006-10-31</td>
 <td style="text-align:center">$1,012</td>
 </tr>,
 <tr>
 <td style="text-align:center">2006-07-31</td>
 <td style="text-align:center">$963</td>
 </tr>,
 <tr>
 <td style="text-align:center">2006-04-30</td>
 <td style="text-align:center">$1,040</td>
 </tr>,
 <tr>
 <td style="text-align:center">2006-01-31</td>
 <td style="text-align:center">$1,667</td>
 </tr>,
 <tr>
 <td style="text-align:center">2005-10-31</td>
 <td style="text-align:center">$534</td>
 </tr>,
 <tr>
 <td style="text-align:center">2005-07-31</td>
 <td style="text-align:center">$416</td>
 </tr>,
 <tr>
 <td style="text-align:center">2005-04-30</td>
 <td style="text-align:center">$475</td>
 </tr>,
 <tr>
 <td style="text-align:center">2005-01-31</td>
 <td style="text-align:center">$709</td>
 </tr>]

In [101]:
data1 = []
for row in rows1[1:]:  # رد header
    cols = row.find_all('td')
    cols_text = [col.text.strip() for col in cols]
    data1.append(cols_text)

In [102]:
cleaned_data1 = []
for row in data1:
    row = row[:2]
    while len(row) < 2:
        row.append(None)
    cleaned_data1.append(row)

In [105]:
gme_revenue = pd.DataFrame(cleaned_data1, columns=["Date", "Revenue"])
gme_revenue['Revenue'] = gme_revenue['Revenue'].replace(r'[\$,]', '', regex=True)
gme_revenue.head()

         Date Revenue
0  2020-04-30    1021
1  2020-01-31    2194
2  2019-10-31    1439
3  2019-07-31    1286
4  2019-04-30    1548

<h1><p><center style="background: linear-gradient(to right,white,green);color: transparent;font-family: Gabriola;color: navy;font-size: 80%;text-align: center;border-radius: 10px 70px">
  
   Question 5: Plot Tesla Stock Graph


</center></p></h1>

In [104]:
def make_graph(stock_data, revenue_data, stock):
    fig = make_subplots(
        rows=2, cols=1,
        shared_xaxes=True,
        subplot_titles=("Historical Share Price", "Historical Revenue"),
        vertical_spacing=0.3
    )

    # Fixed date typo
    stock_data_specific = stock_data[stock_data.Date <= '2021-06-14']
    revenue_data_specific = revenue_data[revenue_data.Date <= '2021-04-30']

    fig.add_trace(
        go.Scatter(
            x=pd.to_datetime(stock_data_specific.Date),
            y=stock_data_specific.Close.astype(float),
            name="Share Price"
        ),
        row=1, col=1
    )

    fig.add_trace(
        go.Scatter(
            x=pd.to_datetime(revenue_data_specific.Date),
            y=revenue_data_specific.Revenue.astype(float),
            name="Revenue"
        ),
        row=2, col=1
    )

    fig.update_xaxes(title_text="Date", row=1, col=1)
    fig.update_xaxes(title_text="Date", row=2, col=1)
    fig.update_yaxes(title_text="Price ($US)", row=1, col=1)
    fig.update_yaxes(title_text="Revenue ($US Millions)", row=2, col=1)

    fig.update_layout(
        showlegend=False,
        height=900,
        title=stock,
        xaxis_rangeslider_visible=True
    )

    fig.show()

In [111]:
tesla_revenue["Date"] = tesla_revenue["Date"].str.replace(r"[^\d-]", "", regex=True)
tesla_revenue["Date"] = pd.to_datetime(tesla_revenue["Date"], errors="coerce")

In [112]:
make_graph(data_ticker , tesla_revenue, 'Tesla')

In [113]:
make_graph(gme_data, gme_revenue, 'GameStop')